/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_rvr_lexerlearning_lexer_Lexer */

#ifndef _Included_dev_rvr_lexerlearning_lexer_Lexer
#define _Included_dev_rvr_lexerlearning_lexer_Lexer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_rvr_lexerlearning_lexer_Lexer
 * Method:    lex
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_rvr_lexerlearning_lexer_Lexer_lex
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dev_rvr_lexerlearning_lexer_Lexer
 * Method:    create
 * Signature: ()Ldev/rvr/lexerlearning/lexer/Lexer;
 */
JNIEXPORT jobject JNICALL Java_dev_rvr_lexerlearning_lexer_Lexer_create
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
